name: iping
description: Una aplicaciÃ³n Flutter para hacer ping a diferentes servidores con estilo Windows
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  intl: ^0.17.0
  sqflite: ^2.2.8
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "icon.png"
  macos:
    generate: true
    image_path: "icon.png"
